{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n  +'1'\n  -1", "trace": "self = <test_allure.TestLogin object at 0x7f9ce652cc10>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登陆\")\n    \n        with allure.step(\"点击登陆之后失败\"):\n>           assert '1'==1\nE           AssertionError: assert '1' == 1\nE             +'1'\nE             -1\n\ntest_allure.py:63: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1613710051231, "stop": 1613710051231}, {"name": "点击密码", "status": "passed", "start": 1613710051231, "stop": 1613710051231}, {"name": "点击登陆之后失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n  +'1'\n  -1\n", "trace": "  File \"/Users/yicg/PycharmProjects/python-demo/16-测试报告美化与定制/test_allure.py\", line 63, in test_login_failure\n    assert '1'==1\n"}, "start": 1613710051231, "stop": 1613710051231}], "start": 1613710051230, "stop": 1613710051231, "uuid": "10541c5d-0937-4119-b004-8550f156526f", "historyId": "ec96e39999f53a6ff844a9debe8d6116", "testCaseId": "52ba3826c163dc76f5affd16329fca3b", "fullName": "test_allure.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登陆模块"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "yichunguangdeMacBook-Pro.local"}, {"name": "thread", "value": "23338-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}